package:
    name: tomcat_h5_writer
    version: 0.0.1

build:
    number: 0

source:
    path: ..

requirements:

    build:
        - make
        - {{ compiler('cxx') }}
        - cppzmq ==4.2.1
        - hdf5 ==1.10.1
        - boost ==1.61.0

    run:
        - cppzmq ==4.2.1
        - hdf5 ==1.10.1
        - boost ==1.61.0


about:
    summary: "Tomcat PCO.EDGE ZMQ to H5 writer."
